# Use postgres/example user/password credentials
version: '3.1'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: next-connect-prisma
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
        ports:
            - '5431:5432'
